version: "3"

services:
  api:
    build: ./excelgpt-backend
    container_name: excelgpt-backend
    restart: always
    # TMP START
    ports:
      - 8000:8000
    volumes:
      - ./excelgpt-backend:/home/excelgpt/app
    # TMP ENB
    secrets:
      - api-secret
    networks:
      - excelgpt-net
  web:
    build: ./excelgpt-frontend
    container_name: excelgpt-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - excelgpt-net
    # TMP START
    volumes:
      - ./excelgpt-frontend:/home/excelgpt/app
    # TMP END
  db:
    image: mariadb:11.1.2
    container_name: excelgpt-db
    restart: always
    secrets:
      - mariadb-root
    # TMP start
    ports:
     - 3306:3306
    # TMP end
    volumes:
      - ./mariadb:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root
    networks:
      - excelgpt-net
  nginx:
    image: nginx:1.25.3-alpine
    container_name: excelgpt-nginx
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    networks:
      - excelgpt-net
    # volumes:
    #   - /etc/letsencrypt/live/coinlocker.link/fullchain.pem:/etc/ssl/live/fullchain1.pem
    #   - /etc/letsencrypt/live/coinlocker.link/privkey.pem:/etc/ssl/live/privkey1.pem



  # queue:
  #   image: rabbitmq:3.12
  #   container_name: excelgpt-queue
  #   ports:
  #     - 5672:5672
  #   networks:
  #     - excelgpt-net

networks:
  excelgpt-net:

secrets:
  mariadb-root:
    file: ./secret/mariadb-root
  api-secret:
    file: ./secret/secret.py

configs:
  nginx-config:
    file: "./nginx/nginx.conf"