version: "3"

services:
  api:
    build: ./excelgpt-backend
    container_name: excelgpt-backend
    restart: always
    # TMP START
    ports:
      - 8000:8000
    volumes:
      - ./excelgpt-backend:/home/excelgpt/app
      - backend-disk:/home/excelgpt/app/disk
      # >secret.py가 복사되지 않는 경우, host에서 추가
      # >경로: /home/excelgpt/app/api/secret.py
    # TMP ENB
    secrets:
      - api-secret
    environment:
      - LIMIT_QUERY_COUNT=100
      - DAYS_EXPIRED_FILES=1
      - DISK_DIR_NAME=disk
    depends_on:
      - db
    networks:
      - excelgpt-net
  web:
    build: ./excelgpt-frontend
    container_name: excelgpt-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - excelgpt-net
    # TMP START
    volumes:
      - ./excelgpt-frontend:/home/excelgpt/app
      - frontend-node_modules:/home/excelgpt/app/node_modules
      - frontend-next:/home/excelgpt/app/.next
    # TMP END
  db:
    image: mariadb:11.1.2
    container_name: excelgpt-db
    restart: always
    secrets:
      - mariadb-root
    # TMP start
    ports:
     - 3306:3306
    # TMP end
    volumes:
      - ./mariadb:/var/lib/mysql:Z
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root
    networks:
      - excelgpt-net
  nginx:
    image: nginx:1.25.3-alpine
    container_name: excelgpt-nginx
    ports:
      - 8888:8888
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    networks:
      - excelgpt-net
    # volumes:
    #   - /etc/letsencrypt/live/coinlocker.link/fullchain.pem:/etc/ssl/live/fullchain1.pem
    #   - /etc/letsencrypt/live/coinlocker.link/privkey.pem:/etc/ssl/live/privkey1.pem



  # queue:
  #   image: rabbitmq:3.12
  #   container_name: excelgpt-queue
  #   ports:
  #     - 5672:5672
  #   networks:
  #     - excelgpt-net

networks:
  excelgpt-net:

secrets:
  mariadb-root:
    file: ./secret/mariadb-root
  api-secret:
    file: ./secret/secret.py

configs:
  nginx-config:
    file: "./nginx/nginx-dev.conf"

volumes:
  backend-app:
  backend-disk:
  frontend-node_modules:
  frontend-next:
  mariadb: